[package]

name = "pb"
version = "0.0.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]

[dependencies]
rustc-serialize = "*"
url = "*"
hyper = "*"

#[dependencies.websocket]
#git = "https://github.com/kstep/rust-websocket.git"

